import React, { useEffect, useMemo, useRef, useState } from 'react';
import { Room, roomsApi } from '../services/api';

interface Props { initialRoomId?: string | null; onGameStart: (room: Room, token: string, playerId: number) => void; }
const tokenKey = (roomId: string) => `perudo-room-token:${roomId}`;

export const MultiplayerLobby: React.FC<Props> = ({ initialRoomId, onGameStart }) => {
  const [room, setRoom] = useState<Room | null>(null); const [name, setName] = useState('Player'); const [token, setToken] = useState<string | null>(null); const [playerId, setPlayerId] = useState<number | null>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(false); const socket = useRef<WebSocket | null>(null);
  const joinUrl = useMemo(() => room ? `${window.location.origin}${window.location.pathname}?room=${room.room_id}` : '', [room]);
  useEffect(() => { if (!initialRoomId) return; roomsApi.get(initialRoomId).then(({ room }) => { setRoom(room); const saved = localStorage.getItem(tokenKey(room.room_id)); if (saved) { setToken(saved); } }).catch(() => setError('Room not found or has expired')); }, [initialRoomId]);
  useEffect(() => { if (!room || !token || playerId === null) return; const ws = roomsApi.connect(room.room_id, token, (event) => { setRoom(event.room); if (event.type === 'game_started' || event.type === 'state_updated') onGameStart(event.room, token, playerId); if (event.type === 'action_rejected') setError(event.error ?? 'Room action was rejected'); }, () => setError('Connection lost; reconnecting…')); socket.current = ws; return () => ws.close(); }, [room?.room_id, token, playerId, onGameStart]);
  const create = async () => { setLoading(true); try { const result = await roomsApi.create(name); setRoom(result.room); setToken(result.player_token); setPlayerId(result.player_id); localStorage.setItem(tokenKey(result.room.room_id), result.player_token); window.history.replaceState({}, '', `?room=${result.room.room_id}`); } catch { setError('Could not create room'); } finally { setLoading(false); } };
  const join = async () => { if (!room) return; setLoading(true); try { const result = await roomsApi.join(room.room_id, name, token); setRoom(result.room); setToken(result.player_token); setPlayerId(result.player_id); localStorage.setItem(tokenKey(room.room_id), result.player_token); } catch { setError('Could not join this room'); } finally { setLoading(false); } };
  const start = async () => { if (!room || !token || playerId === null) return; setLoading(true); try { const result = await roomsApi.start(room.room_id, token); onGameStart(result.room, token, playerId); } catch { setError('Только автор комнаты может запустить игру, когда заняты все 4 места'); } finally { setLoading(false); } };
  const joined = token !== null && playerId !== null; const occupied = room?.seats.filter((s) => s.seat_type === 'human').length ?? 0;
  return <div className="min-h-full bg-gray-800 text-white flex justify-center p-4 sm:p-8"><div className="w-full max-w-4xl space-y-6"><section><h2 className="text-4xl font-bold text-orange-400">Perudo Room</h2><p className="text-gray-300 mt-2">Игра для 4 человек. Автор комнаты может начать игру, когда заняты все места.</p></section><div className="bg-gray-700/70 rounded-lg p-4 flex flex-col sm:flex-row gap-3"><input value={name} maxLength={32} onChange={(e) => setName(e.target.value)} className="flex-1 px-4 py-2 bg-gray-600 rounded-lg" placeholder="Your name" />{!room ? <button onClick={create} disabled={loading} className="px-5 py-2 bg-green-600 rounded-lg font-semibold">Create room</button> : !joined ? <button onClick={join} disabled={loading} className="px-5 py-2 bg-green-600 rounded-lg font-semibold">Join room</button> : null}</div>{room && <><section className="bg-gray-700/70 rounded-lg p-4"><div className="flex justify-between gap-4"><div><div className="text-sm uppercase text-gray-400">Join code</div><div className="text-3xl font-bold text-yellow-300">{room.join_code}</div></div><button onClick={() => navigator.clipboard?.writeText(joinUrl)} className="px-4 py-2 bg-gray-600 rounded-lg">Copy invite link</button></div><p className="mt-3 text-sm text-gray-300 break-all">{joinUrl}</p></section><section className="grid grid-cols-1 sm:grid-cols-2 gap-4">{room.seats.map((seat) => <div key={seat.player_id} className="bg-gray-700/70 rounded-lg p-4"><div className="text-sm text-gray-400">Seat {seat.player_id + 1}</div><div className="text-2xl font-bold">{seat.player_name ?? 'Waiting for player'}</div><div className="text-sm text-gray-300">{seat.player_name ? (seat.is_connected ? 'Online' : 'Offline') : 'Empty'}</div></div>)}</section>{joined && <button onClick={start} disabled={loading || occupied < 4} className="w-full px-4 py-3 bg-green-600 disabled:bg-gray-600 rounded-lg font-semibold">Start game ({occupied}/4 players)</button>}</>}{error && <p className="text-red-300">{error}</p>}</div></div>;
};
